### ISSUE TITLE
PNG is not working

### ISSUE THREAD

**Issue by Ramishscrapper** [abdarker/image-compressor#2]
There's something issue we cannot compress the png file

![image](https://github.com/abdarker/image-compressor/assets/64010918/2f807bc7-e66b-4a02-a708-573eb6a941ef)

There's one more issue when we download image from the zip the compressed image download in the same format in which the image upload but when we download image from the button of the uploaded it will always download in the jpg format

**Comment by abdarker** [comment]
i am aware of that. when it comes compressing png the compression logic a bit different. i have tried different approach but i couldn't find any optimal solution for that. so i set the minimum PNG file size to 300kb. 

and for the 2nd issue that you have mentioned yeah i just noticed i did a mistake there. i will fix it.

**Comment by abdarker** [comment]
i set the minimum image size for png to be 120kb and the download single image in same format as uploaded  format. issue is fixed. thanks
